import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Cormorant_Garamond, Lora } from 'next/font/google';

// Configure Cormorant Garamond (supports weights 300-700, italic)
const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  variable: '--font-cormorant',
});

// Configure Lora (supports weights 400-700, italic)
const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  variable: '--font-lora',
});

export const metadata = {
  title: "Regine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cormorant.variable} ${lora.variable}`}>
      <body
   
      >
        {children}
      </body>
    </html>
  );
}
